# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  target 'UpChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpChallenge
  # pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  # pod 'SnapKit', '~> 3.2.0'
  # pod 'Alamofire', '~> 4.4.0'
   pod 'SwiftyJSON', '~> 3.1.4'
  # pod 'RealmSwift', '~> 2.4.4'
  # pod 'FontAwesome.swift', '~> 1.0.0'
  
  target 'UpChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UpChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
